### ISSUE TITLE
errors when installing packages

### ISSUE THREAD

**Issue by LexiestLeszek** [mlc-ai/package#25]
Building the ios app according to the instruction. My machine is Mac M1 2020 and IDE is VSCode. 
On the stage of installing TVM Unity package I type this: pip3 install --pre --force mlc-ai-nightly mlc-chat-nightly -f https://mlc.ai/wheels 

And have this in the terminal:
Looking in links: https://mlc.ai/wheels
Collecting mlc-ai-nightly
  Downloading https://github.com/mlc-ai/package/releases/download/v0.9.dev0/mlc_ai_nightly-0.12.dev1095%2Bgd1e3142ac-cp311-cp311-macosx_13_0_arm64.whl (59.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.6/59.6 MB 4.7 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement mlc-chat-nightly (from versions: none)
ERROR: No matching distribution found for mlc-chat-nightly

**Comment by tqchen** [comment]
Thanks for reporting, we are still working on it, will report back once it is ready

**Comment by LexiestLeszek** [comment]
Sure!

For now, can I maybe install any other versions of mlc-ai-nightly and mlc-chat-nightly for it to work?

**Comment by tqchen** [comment]
` mlc-ai-nightly` should be installable already, and that should be sufficient if you don't want to use the rest api

**Comment by LexiestLeszek** [comment]
I still have the same error for some reason with mlc-chat-nightly.

ooking in links: https://mlc.ai/wheels
Collecting mlc-ai-nightly
  Downloading https://github.com/mlc-ai/package/releases/download/v0.9.dev0/mlc_ai_nightly-0.12.dev1140%2Bg206661b4a-cp311-cp311-macosx_13_0_arm64.whl (81.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.8/81.8 MB 4.6 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement mlc-chat-nightly (from versions: none)
ERROR: No matching distribution found for mlc-chat-nightly

**Comment by yzh119** [comment]
@LexiestLeszek wheels for Mac arm64 are uploaded, please try it again and see if your concerns have been resolved

**Comment by LexiestLeszek** [comment]
Thanks, now everything works.
