### ISSUE TITLE
mlc-chat nightly for python 3-9 (arm64) not released

### ISSUE THREAD

**Issue by javixeneize** [mlc-ai/package#54]
Hi

I am trying to install mlc-chat nightly, and the wheel for python 3.9 arm64 has not been released - https://mlc.ai/wheels

Could this be added please?

Thanks

**Comment by junrushao** [comment]
I believe this is released as `mlc_chat_nightly-0.1.dev456-cp39-cp39-macosx_13_0_arm64.whl`
